version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: per
    image: dtuncbilek/per:1.0.7
    restart: unless-stopped
    ports:
      - "4242:80"

#first use this
# first off all, you must docker-desktop app run. and then check the image version as amd64
# ng build
# docker build --platform linux/amd64 -t dtuncbilek/per:1.0.7 .
# docker push dtuncbilek/per:1.0.7


# if doesnt work use this...
# docker compose build
# docker push dtuncbilek/per:1.0.6

