version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lid
    image: mkargaci/per:1.0.1
    restart: unless-stopped
    ports:
      - "4242:80"

# first use this...
# docker compose build
# docker push mkargaci/per:1.0.1

